# Generated by Django 4.2 on 2023-05-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemarket', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
