# Generated by Django 4.2 on 2023-05-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemarket', '0006_order_last_name_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
